### ISSUE TITLE
The program doesn't start (Win8 ; same in Win 7, XP compatibility mode)

### ISSUE THREAD

**Issue by xt0pher** [jloehr/Wiimote-Buzzer#1]
Hi,
This is a great tools but impossible to start it. I've downloaded it 3 times.
Perhaps you should try on your own computer (download form github link, uncompress & install, or maybe reupload it correctly here !?

Many greetz.
xtopher

**Comment by jloehr** [comment]
Yeah, i noticed myself. Seems to be a missing Runtime Lib.It works on Windows 10, but i don't know whether it is simply Windows 10 or the fact i have Development Tools installed. I'll look into this, as i need the same setup for another Project.

**Comment by jloehr** [comment]
Here you go: https://github.com/jloehr/Wiimote-Buzzer/releases/tag/v1.0.1.0.
I tested it on my Windows 7 Test-VM, therefore i assume it'll also work on Windows 8 and 10.
If not already installed, Visual C++ 2015 is required (matching the architecture of the zip).

**Comment by xt0pher** [comment]
Hello,

Thanks so much ! You’re fast ... It works perfectly now ! 
A great tools. I’ve posted it on wii-info.

Have a nice day.
xtopher
